### ISSUE TITLE
Optionally computing only a subset of the score matrix in M2M tests

### ISSUE THREAD

**Issue by rgutzen** [scidash/sciunit#109]
M2M tests produce score matrices of the size N, where N is the number of models passed to the judge function. In many cases, this matrix contains redundant information (when the type of score is symmetric) and irrelevant information (comparing models to themselves). Thus, an optional argument to the judge function, selecting only a certain combination of models to be compared can streamline the validation, and especially for computationally expensive score calculations, decrease the run time.
I would think of an argument defining the locations in the score matrix that are of interest:
`test.judge([model1, model2, model3, model4], loc=[(0,1), (0,2), (0,3), (1,3)]) `

**Comment by rgerkin** [comment]
Do you think you will just want to calculate the lower triangle of the matrix (without the diagonal), or will it be important to pick specific locations in that lower triangle?  In the example above, you omit (1, 2), which would mean it would be slightly faster than doing the whole lower triangle.

**Comment by rgutzen** [comment]
The most common case would definitely be to select the lower triangle. Another usual scenario that comes to mind is to compare one model (or observation) to many others, but not compare between them. However, this scenario is equivalent to calling the judge function multiple. Thus, the option to select the lower triangle would suffice for now, as more complex combinations of comparisons can then be constructed.

**Comment by rgerkin** [comment]
@rgutzen 
I've added this in the dev branch in 73fc350f6fb9504e3655fd7fe254e1679fa9f6d4, and [here](https://github.com/scidash/sciunit/blob/dev/sciunit/unit_test/test_only_lower_triangle.ipynb) is a demo.  

When the `only_lower_triangle` kwarg is set to `True` in `TestM2M.judge`, It computes only the lower triangle (oops, maybe it is the upper triangle... I'll change the name later).  It copies those results to the upper (lower) triangle.  It also skips the diagonal and assumes the entries on the diagonal should have perfect scores.  I added a `_best` attribute to Score classes so that the new method `Test.ace` can know what the best possible score is for that score type, and assign it with no actual computation.  

In the notebook you can see that in general there may be asymmetry in a measure of model agreement, for example when using `RatioScore` you get a score of X going one way and a score of 1/X going the other way.  You can always devise a score type that doesn't have this problem.  Until then, the full computation of all model vs. model scores will differ from the faster version that only does the lower triangle by this factor, as the notebook shows.  

Let me know if you want any other changes before I merge this into master.

**Comment by rgutzen** [comment]
That's great, thanks! Also, the `_best` and `_worst` attributes for Scores are a very helpful addition.
