### ISSUE TITLE
tkinter import error on headless system

### ISSUE THREAD

**Issue by andrisecker** [scidash/sciunit#133]
I can't `import sciunit` on a cluster because there is no tkinter installed...
and I can't do `sudo apt-get install python-tk`

Would it be possible to put `import tkinter` into a try block (something like https://github.com/scidash/sciunit/blob/master/sciunit/utils.py#185 ) and then set `matplotlib.use('agg')` if it can't import instead of first importing it and then check for it?

**Comment by rgerkin** [comment]
@andrisecker Do you know which tkinter import or usage line is causing the problem (what file and line)?  You can just paste the stack trace if you want.

**Comment by andrisecker** [comment]
@rgerkin sorry for not being too specific:
the tkinter import in the beginning of utils.py - line 35:
`from .base import SciUnit, FileNotFoundError, tkinter`

**Comment by rgerkin** [comment]
@andrisecker Is the error that tkinter is not there (in .base) to import, or is there some problem importing tkinter in general?  Can you run `import tkinter` on your system in general?

**Comment by rgerkin** [comment]
@andrisecker I just made a commit to the dev branch that should ensure that `tkinter` will always exist in `.base` to be imported, even for Python 2.x without Tkinter (is that what you are using?).  For now, that is the only change I can see that could help so perhaps you can try that out.  Then you might try:  
```
import sciunit
import matplotlib as mpl
mpl.use('Agg')
```
before running any other sciunit code that might invoke the display.

**Comment by andrisecker** [comment]
Thanks @rgerkin ! (I'm using Python 3.6)

**Comment by rgerkin** [comment]
@andrisecker Could you still put the stack trace here?  I'm not sure how in Python 3.6 it could fail to import tkinter from .base (which just imports tkinter directly in Python 3.x, see [this line](https://github.com/scidash/sciunit/blob/f4196821037a7dd886c38d5b442480b223799257/sciunit/base.py#L28)).

**Comment by andrisecker** [comment]
sure this is the error I had:
```
/opt/app-root/lib/python3.6/site-packages/sciunit/__init__.py in <module>
      8 from __future__ import unicode_literals
      9 
---> 10 from .utils import settings, log
     11 from .models import Model
     12 from .capabilities import Capability

/opt/app-root/lib/python3.6/site-packages/sciunit/utils.py in <module>
     33 import sciunit
     34 from sciunit.errors import Error
---> 35 from .base import SciUnit, FileNotFoundError, tkinter
     36 from .base import PLATFORM, PYTHON_MAJOR_VERSION
     37 try:

/opt/app-root/lib/python3.6/site-packages/sciunit/base.py in <module>
     26 else:
     27     from io import StringIO
---> 28     import tkinter
     29     FileNotFoundError = FileNotFoundError
     30 

ModuleNotFoundError: No module named 'tkinter'
```

**Comment by rgerkin** [comment]
@andrisecker I was under the impression that `tkinter` was part of the Python standard library, but I see (e.g. [here](https://discuss.python.org/t/importerror-no-module-named-tkinter/2448/2)) that in some distributions it is not included.  One solution is for someone to `sudo apt-get install python-tk` or the equivalent on your server.  But I've also just wrapped `import tkinter` it in a try/except block in the [latest commit](892ddbbb0cff1e432b3403b4d56e1d0232ae8376) on the dev branch, so that should also fix your problem if you want to use that branch until I create a new release.

**Comment by andrisecker** [comment]
yeah I can't do `apt-get install python-tk` on the server, I can only pip install packages.
Wrapping the import to a try block was what I meant from the start, sorry if it wasn't clear.

**Comment by rgerkin** [comment]
@andrisecker Right, I just didn't want to commit the user to any specific matplotlib backend so early in the code.  Let me know if the dev branch works for you.

**Comment by appukuttan-shailesh** [comment]
@rgerkin : Sorry to dig up this closed ticket.
It would be nice if we can incorporate the fix for this (https://github.com/scidash/sciunit/commit/892ddbbb0cff1e432b3403b4d56e1d0232ae8376) into master, and released on PyPI.

We are having problems in using sciunit on Py3 inside the HBP's new Collaboratory (v2). `tkinter` isn't available on this system, and we can only install via `pip`, so unable to install this package.

**Comment by rgerkin** [comment]
I've just merged that fix into master (I should have done that a long time ago) and pushed a new version to pypi: https://pypi.org/project/sciunit/0.2.2.3/.

**Comment by appukuttan-shailesh** [comment]
Great. Thanks for the quick response :-)
