### ISSUE TITLE
Caching strategy for test results

### ISSUE THREAD

**Issue by cyrus-** [scidash/sciunit#15]
Need to figure out how to avoid having to rerun every test-model combination when only one has updated (using a file + checksum based on the source code of the test + the values of its parameters, or something like that; maybe using SQLite?)

**Comment by rgerkin** [comment]
I am leaving some of this for domain specific implementations.  Otherwise sciunit.utils.method_cache and sciunit.utils.method_memoize (cypy.memoize) should work fine for this.  I am going to look into the possibilty of porting the NeuronUnit MemoryBackend and DiskBackend implementations to SciUnit, but I'm not sure how I can make them completely generic since what corresponds to cachable Model attibutes may depend on how that Model class is defined.

**Comment by rgerkin** [comment]
NeuronUnit now has caching in its parent Backend class, handled in such a way as to avoid using a cached result if a backend (i.e. a simulator) changed, since in that case you might not want to rely on the old result.
