### ISSUE TITLE
Generating predictions based on target observation

### ISSUE THREAD

**Issue by appukuttan-shailesh** [scidash/sciunit#169]
I was wondering if it would be useful to allow the generation of model prediction based on the target reference data. As an example, I have my observation data in the following format:
```
obs_data = { 0.2: A, 0.4: B, 0.6: C, 0.8: D, 1.0: E}
```
where the keys (0.2, 0.4, ...) are floats that indicate the intenstity of injected current, and the values (A, B, ...) are integers/floats that indicate the firing rate.

I would like my test to run for all the current intensities as are available as keys in the target observation data. I believe, I could currently access `self.observation` inside `generate_prediction()` to do this. But if permitting this approach, wouldn't it be better to move call to [`validate_observation()`](https://github.com/scidash/sciunit/blob/master/sciunit/tests.py#L256) above [`generate_prediction()`](https://github.com/scidash/sciunit/blob/master/sciunit/tests.py#L251) within [`_judge()`](https://github.com/scidash/sciunit/blob/master/sciunit/tests.py#L245)

Are there any cons to this move of validating the observation before generating the model prediction? I believe this might help in identifying any errors (in the observation) earlier and avoid unnecessary generation of model predictions in such cases.

**Comment by rgerkin** [comment]
I think this makes sense.  An argument against it would be if the prediction itself could be used to validate the observation.  For example, what if `generate_prediction()` returns something, say a `dict`, whose keys the `observation` should contain, but it cannot be known in advance what these keys will be.  Maybe that would a be a very uncommon use case, and since you have an actual use case requiring the opposite order, I'd be happy to accept a PR which changes the order.

**Comment by appukuttan-shailesh** [comment]
Thanks @rgerkin!
I have now made a PR..... let me know if anything needs changing.

**Comment by rgerkin** [comment]
@appukuttan-shailesh I've merged it.  Do you need a new release from this?

**Comment by appukuttan-shailesh** [comment]
Thanks @rgerkin. No hurry for the new release, it can wait.
For now I am fairly confident about my input obeservation data, so not too worried about its validation.
