### ISSUE TITLE
Multiple score_type for same test

### ISSUE THREAD

**Issue by appukuttan-shailesh** [scidash/sciunit#213]
Is it possible to specify multiple values for `score_type` for a single test? I have tried doing something like:
```score_type = [NAScore, ZScore, KLdivMeanStd]```
but doesn't seem to work.

This is for handling situations, for example, where the model is stochastic and we record all the spikes for some analysis (say, AP width).
The possible cases are:
(i) No spikes (prediction = None)
(ii) Single spike (prediction = value)
(iii) Multiple spikes (prediction = {mean, std})

Based on the prediction, I might need to score using `InsufficientDataScore` or `ZScore`, something else
What is the best way to handle this?

While on this topic... do you have recommendations for a good scoring metric when both obs & pred are distrubtions (i.e. have mean, std)?

**Comment by rgerkin** [comment]
I don't think it will work as written because eventually Test.score_type() will be called to instantiate a score, so that won't work directly on a list.  Where this occurs, you could imagine fixing Sciunit to iterating through the list of score_types with a try/except block for each until you get the one that matches your case.  This isn't ideal, though.

When both obs & pred are distributions I use [CohensDScore](https://sciunit.readthedocs.io/en/latest/_modules/sciunit/scores/complete.html#CohenDScore), or you could extend this into a new Kullback-Leibler score, although maybe that is what your `KLdivMeanStd` is above.  I think Cohen's D is more interpretable, though.

**Comment by appukuttan-shailesh** [comment]
Thanks @rgerkin ... do you have any examples that currently handle "Not Applicable" cases (e.g. capability not satisfied, or prediction not as required, etc) when models run tests..... where an error isn't raised, but the score is set to null or NA or similar. I see this situation arising when running Test Suites, where a few might be failing.

Yes, `KLdivMeanStd` was an implementation of the Kullback-Leibler score. But I am not totally convinced of using it yet. Will take a look at CohensDScore. Thanks!

**Comment by rgerkin** [comment]
One of the scores in the [scores/incomplete.py](https://github.com/scidash/sciunit/blob/master/sciunit/scores/incomplete.py) module might help.  The usual workflow is for your `compute_score` to just return an instance of one of these instead of an instance of whatever `Test.score_type` happens to be.
