### ISSUE TITLE
Add score_key and score_type to score json serialization 

### ISSUE THREAD

**Issue by gidili** [scidash/sciunit#64]

**Comment by rgerkin** [comment]
@gidili 
See the dev branches of [sciunit](https://github.com/scidash/sciunit/blob/dev/sciunit/__init__.py#L126) and [neuronunit](https://github.com/scidash/neuronunit/blob/dev/neuronunit/unit_test/serialization_test.ipynb) for the new implementation.  

Because the attributes you requested are actually properties (methods with the property decorator), they do not actually represent the state of the object, but rather a computation done on the object.  If these attributes were present in the serialized form, then it would not de-serialize back to the original object, but to one with values replacing methods.  So I left the default behavior of the `json` method to serialize without the properties, and added a keyword argument to `add_props`.  So e.g. `score.json()` will give the serialization without the properties, and `score.json(add_props=True)` will give the serialization with them (which is what you requested).  I also added `keys` and `exclude` keyword arguments to give you finer control over the contents of the serialization, if you need it.  Note that `json` is now a regular method and not a property, so `score.json` without the parentheses will return the method and not its result.

**Comment by gidili** [comment]
Thanks @rgerkin I see in the new example that sort key (`'sort_key': 0.7388826803635273,`) and score class (`'_class': 'ZScore'`) are coming up for the score serialisation when `add_props=True` 👍 

Also we had talked about adding model class info and test class info to the serialized object and I see that those are also coming up with the add_props flag set to to true as follows:

- `'model': {'_class': 'ReducedModel'`
- `'test': {'_class': 'MyTest',`

Can you confirm that we can/should use those values to populate those fields (model/test class) and that no other metadata for model/test class is initially needed but pretty much the name of the class is enough for now?

**Comment by rgerkin** [comment]
It looks like we will need to expand the `model` field to something like: 
```'model': {'_class': {'name': 'ReducedModel', 'url': 'url_string', 'version', 'hash_string'}}```

**Comment by gidili** [comment]
And the same for test class, right? 

Sorry I meant to write a recap of our chat yesterday night but I forgot I had to pack as I’m traveling till Sunday.

**Comment by rgerkin** [comment]
Yes, that too.  I just wanted to put something down here before I forgot.

**Comment by rgerkin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Metacell](https://trello.com/c/pg461sPp/1-metacell)

**Comment by rgerkin** [comment]
Implemented in 5467d6ce58dedf32771437d8883595fb86b9092f and in code related to MetaCell/geppetto-scidash#30
